export const getAllProducts = () => {
  return [
    {
      id: "NAF-1-07-FMEN-001",
      slug: "nike-air-force-1-07-men",
      name: "Nike Air Force 1 '07",
      category: `Men's Shoes`,
      categorySlug: "men-shoes",
      price: 1_549_000,
      stock: 100,
      imageUrl: "/assets/images/AIR-FORCE-1-07.png",
      description: `The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.`,
    },
    {
      id: "NAF-1-07-FMEN-LV8-002",
      slug: "nike-air-force-1-07-lv8-men",
      name: "Nike Air Force 1 '07 LV8",
      category: `Men's Shoes`,
      categorySlug: "men-shoes",
      price: 1_909_000,
      stock: 5,
      imageUrl: `/assets/images/AIR+FORCE+1+'07+LV8.png`,
      description: `Comfortable, durable and timeless—it's number 1 for a reason. The classic '80s construction pairs with bold details for style that tracks whether you're on court or on the go.`,
    },
    {
      id: "NAF-1-07-FWOMEN-003",
      slug: "nike-air-force-1-07-women",
      name: "Nike Air Force 1 '07",
      category: `Women's Shoes`,
      categorySlug: "women-shoes",
      price: 1_909_000,
      stock: 0,
      imageUrl: `/assets/images/WMNS+AIR+FORCE+1+'07.jpeg`,
      description: `Comfortable, durable and timeless—it's number 1 for a reason. The classic '80s construction pairs a warm suede upper with neutral accents for style that tracks whether you're on court or on the go.`,
    },
    {
      id: "NAF-1-07-FWOMEN-003",
      slug: "nike-air-force-1-07-women",
      name: "Nike Air Max Koko '07",
      category: `Women's Shoes`,
      categorySlug: "women-shoes",
      price: 1_429_000,
      stock: 0,
      imageUrl: `/assets/images/nikeairmax.png`,
      description: `Heat up the streets in the Nike Air Max Koko Sandal. Designed for women, this pinnacle platform height sandal adds a splash of colourful Air in the heel. The thick, layered foam midsole provides a smooth and flexible ride. Premium details on the upper add texture and dimension to elevate your look.`,
    },
    {
      id: "NAF-1-07-FMEN-001",
      slug: "nike-air-force-1-07-men",
      name: "Nike Vista'07",
      category: `Men's Shoes`,
      categorySlug: "men-shoes",
      price: 759_000,
      stock: 100,
      imageUrl: "/assets/images/nikevista.png",
      description: `With all of the necessary elements you need for a day out (like plush padding and easy-to-style colours), the Nike Vista delivers on less is more. Lightweight, airy and supportive, it lets you bridge city living and nature with the pull of a strap.`,
    },
  ];
};
